#!/usr/bin/env python3
"""Test Piped API instances for captions"""
import requests, json

instances = [
    "https://pipedapi.kavin.rocks",
    "https://pipedapi.r4fo.com",
    "https://pipedapi.adminforge.de",
    "https://api.piped.projectsegfau.lt",
    "https://pipedapi.moomoo.me",
    "https://watchapi.whatever.social",
    "https://piped-api.privacy.com.de",
]

video_id = "o9JvO7MGQPo"
headers = {"User-Agent": "Mozilla/5.0"}

for inst in instances:
    try:
        # Piped streams endpoint includes captions
        url = f"{inst}/streams/{video_id}"
        r = requests.get(url, headers=headers, timeout=10)
        if r.status_code == 200:
            data = r.json()
            subs = data.get("subtitles", [])
            print(f"OK  {inst} - {len(subs)} subtitle tracks")
            for sub in subs:
                print(f"    {sub.get('code')}: {sub.get('autoGenerated')} - {sub.get('url','')[:80]}")
            if subs:
                # Try downloading
                sub_url = subs[0].get("url")
                if sub_url:
                    r2 = requests.get(sub_url, headers=headers, timeout=10)
                    print(f"    Download: {r2.status_code}, len={len(r2.text)}")
                    print(f"    Preview: {r2.text[:200]}")
                break
        else:
            print(f"ERR {inst} - HTTP {r.status_code}")
    except Exception as e:
        print(f"ERR {inst} - {str(e)[:60]}")
